image: cloudfoundry/diego-pipeline

env:
  - GOROOT=/usr/local/go
  - BOSH_USER={{BOSH_USER}}
  - BOSH_PASSWORD={{BOSH_PASSWORD}}
  - BOSH_TARGET={{BOSH_TARGET}}
  - INFRASTRUCTURE={{INFRASTRUCTURE}}
  - DEPLOYMENT_NAME={{DEPLOYMENT_NAME}}
  - GINKGO_PARALLEL={{GINKGO_PARALLEL}}
  - GO_PIPELINE_COUNTER={{GO_PIPELINE_COUNTER}}
  - GO_STAGE_NAME={{GO_STAGE_NAME}}
  - SHORT_TIMEOUT={{SHORT_TIMEOUT}}
  - LONG_TIMEOUT={{SHORT_TIMEOUT}}

script:
  - ./scripts/pipeline

cache:
  - /tmp/cache
  - cf-release/.blobs
  - output
  - .blobs
