image: cloudfoundry/diego-pipeline

env:
  - GOROOT=/usr/local/go
  - BOSH_USER={{BOSH_USER}}
  - BOSH_PASSWORD={{BOSH_PASSWORD}}
  - BOSH_TARGET={{BOSH_TARGET}}
  - DEPLOYMENT_NAME={{DEPLOYMENT_NAME}}

script:
  - ./scripts/pipeline

cache:
  - /tmp/cache

deploy:
  git:
    target: git@github.com:cloudfoundry-incubator/diego-release.git
    force: true
    branches:
      develop: passed-integration
      passed-integration: passed-deploy
      passed-deploy: master
