iaas_settings:
  stemcell:
    name: (( merge ))
    version: (( merge ))
  subnet_configs:
    - name: diego1_windows
      subnets: (( merge ))
    - name: diego2_windows
      subnets: (( merge ))
    - name: diego3_windows
      subnets: (( merge ))
  compilation_cloud_properties: (( merge ))
  resource_pool_cloud_properties:
    - name: windows_z1
      cloud_properties: (( merge ))
    - name: windows_z2
      cloud_properties: (( merge ))
    - name: windows_z3
      cloud_properties: (( merge ))
