image: cloudfoundry/diego-pipeline

env:
  - GOROOT=/usr/local/go
  - BOSH_USER={{BOSH_USER}}
  - BOSH_PASSWORD={{BOSH_PASSWORD}}
  - BOSH_TARGET={{BOSH_TARGET}}
  - DEPLOYMENT_NAME={{DEPLOYMENT_NAME}}
  - DATADOG_API_KEY={{DATADOG_API_KEY}}

script:
  - ./scripts/ci/create_diego_release_inner

cache:
  - /tmp/cache
