image: cloudfoundry/diego-pipeline

env:
  - GOROOT=/usr/local/go
  - GO_PIPELINE_COUNTER={{GO_PIPELINE_COUNTER}}
  - FINAL_RELEASE_VERSION_OFFSET={{FINAL_RELEASE_VERSION_OFFSET}}

script:
  - ./scripts/ci/create_final_release_inner

cache:
  - /tmp/cache
  - cf-release/.blobs
  - output
  - .blobs
