image: cloudfoundry/diego-pipeline

env:
  - GOROOT=/usr/local/go
  - BOSH_USER={{BOSH_USER}}
  - BOSH_PASSWORD={{BOSH_PASSWORD}}
  - BOSH_TARGET={{BOSH_TARGET}}
  - SMOKE_TESTS_MANIFEST={{SMOKE_TESTS_MANIFEST}}

script:
  - ./scripts/ci/run_diego_smoke_tests_inner
