image: cloudfoundry/diego-pipeline

env:
  - GOROOT=/usr/local/go
  - BOSH_USER={{BOSH_USER}}
  - BOSH_PASSWORD={{BOSH_PASSWORD}}
  - BOSH_TARGET={{BOSH_TARGET}}
  - DEPLOYMENT_NAME={{DEPLOYMENT_NAME}}

script:
  - ./scripts/ci/run_diego_cats_inner
