image: cloudfoundry/diego-pipeline

env:
  - GOROOT=/usr/local/go
  - DEFAULT_EVENTUALLY_TIMEOUT={{DEFAULT_EVENTUALLY_TIMEOUT}}
  - GINKGO_PARALLEL={{GINKGO_PARALLEL}}

script:
  - ./scripts/ci/run_inigo_inner
