image: cloudfoundry/diego-pipeline

env:
  - GOROOT=/usr/local/go
  - BOSH_USER={{BOSH_USER}}
  - BOSH_PASSWORD={{BOSH_PASSWORD}}
  - BOSH_TARGET={{BOSH_TARGET}}
  - ACCEPTANCE_TESTS_MANIFEST={{ACCEPTANCE_TESTS_MANIFEST}}

script:
  - ./diego-release/scripts/ci/run_diego_cats_inner
