image: cloudfoundry/diego-pipeline

env:
  - GOROOT=/usr/local/go
  - BOSH_USER={{BOSH_USER}}
  - BOSH_PASSWORD={{BOSH_PASSWORD}}
  - BOSH_TARGET={{BOSH_TARGET}}

script:
  - ./scripts/ci/upload_stemcell_inner
