---
rootfs/lucid64.tar.gz:
  object_id: bc2519cd-c93c-4e8e-8bf4-becf889dabe7
  sha: !binary |-
    YWI1Njg2MWMyNGEzOTQ2YzMzYmFiYzVkYjJiMGRjZDVhYWQxYzI4YQ==
  size: 257769231
iptables/iptables-1.4.21.tar.bz2:
  object_id: 1c0b0768-4ea9-4d70-a9f2-06fd3c77c092
  sha: !binary |-
    ODVkNDE2MDUzNzU0NmEyM2E3ZTQyYmMyNmRkN2VlNjJhMGVkZTRjOA==
  size: 547439
golang/go1.3.1.linux-amd64.tar.gz:
  object_id: 233b6d72-2225-4d39-aced-5693f14b33cc
  sha: !binary |-
    M2FmMDExY2MxOWIyMWM3MTgwZjI2MDRmZDg1ZmJjNGRkZGU5NzE0Mw==
  size: 51930765
shadow/shadow-4.2.1.tar.gz:
  object_id: 8f17023f-2a94-4d98-a737-ddbf166e7188
  sha: !binary |-
    MWQyMDU0MTg4NjNkZDAyYjJiOGFmMGZhNzhmY2NlNWQ3Yzg0OGQxZg==
  size: 3686676
cf-cli/cf-linux-amd64.tgz:
  object_id: 851a4bac-d201-4f85-acca-a09f6ee8aabe
  sha: !binary |-
    NjJjMTc1YTI4OTQwNjI0NDlkNmE0NDVjOWFhMTczNTczYzg1OGQ5Zg==
  size: 4367617
