---
golang/go1.2.linux-amd64.tar.gz:
  object_id: da9936cd-3abe-4cad-90c7-63c25bd1839a
  sha: !binary |-
    NjY0ZTUwMjVlYWU5MTQxMmE5NmExMGY0ZWQxYThhZjZmMGYzMmI3ZA==
  size: 55966325
git/git-1.7.11.2.tar.gz:
  object_id: b38d3ef1-9363-430e-a6a7-15ee78efa397
  sha: !binary |-
    ZjY3YjRmNmMwMjc3MjUwNDExYzY4NzJhZTdiOGE4NzJhZTExZDMxMw==
  size: 4015780
rootfs/lucid64.tar.gz:
  object_id: d52047e1-2992-4800-85f8-a15fdd584dea
  sha: !binary |-
    YjI2MzNiMmFiNDk2NGY5MTQwMmJiMmQ4ODlmMmYxMjQ0OWE4YjgyOA==
  size: 199489185
etcd/etcd-v0.2.0.tar.gz:
  object_id: 5dc1b0b3-c456-40f8-b9e3-5a409df4d480
  sha: !binary |-
    YzE4YmZlNTMzYTVjMTgwMDEyMTg4ZTQwMzliNzQwYjk1NjQ4OTRjZQ==
  size: 1500812
