version: 1
update_configs:
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "daily"
    target_branch: "develop"
    default_labels:
      - "dependencies"
      - "security"
    allowed_updates:
    - match:
        update_type: "security"
