---
packages:
- name: golang
  version: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  sha1: !binary |-
    ZDBlMDA5MmU5MDZmNTY1YzYxMTNkNzk1MGExZDU0YTk5MWRmYjM4Mg==
  fingerprint: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  dependencies: []
- name: rep
  version: !binary |-
    OGE5YTk0MDBlZDQwY2Q0NjliNDNlYWNkYjJhODAyZDA4YTM0NTY2OA==
  sha1: !binary |-
    ZGNjYmQ0MzZlNTQ1YTUwOGQ1OWMzZmE4MTU4YWMzYmQ5MDAxMjQ2OA==
  fingerprint: !binary |-
    OGE5YTk0MDBlZDQwY2Q0NjliNDNlYWNkYjJhODAyZDA4YTM0NTY2OA==
  dependencies:
  - golang
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    ODZhYjg4MmY4MTkxZjBjOGU2ZjVmYWVlYTBhOTE3M2MxMTkwZTA3ZQ==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  dependencies: []
- name: linux-circus
  version: !binary |-
    ZTg5OTM0YzIyNmIxZDY4MDJjYjg0ZGE0OTg0ODM3NWU0MTM0MzI4MA==
  sha1: !binary |-
    NzdmYzBmMTkxY2Y5N2U5N2M4OWE1MjhkM2JhOTMwY2I0YTczMGQ2ZQ==
  fingerprint: !binary |-
    ZTg5OTM0YzIyNmIxZDY4MDJjYjg0ZGE0OTg0ODM3NWU0MTM0MzI4MA==
  dependencies:
  - golang
- name: etcd_metrics_server
  version: !binary |-
    OTdhMWFhYWVmOGM2ZmYzZGNjYTkzYjMxNjViZTZmOGViODc2YzJkMQ==
  sha1: !binary |-
    OTg3Zjg5OTFhMTUzZWI2ZjVlNDI2NzMwMGJlZDA4MDY1M2Y0Njg0Ng==
  fingerprint: !binary |-
    OTdhMWFhYWVmOGM2ZmYzZGNjYTkzYjMxNjViZTZmOGViODc2YzJkMQ==
  dependencies:
  - golang
- name: tps
  version: !binary |-
    OGUwYjQ4Yzk1MDkzMGI4OTQ2NTkyZDlhYjAyZTFkOGExNmJjMmYxMA==
  sha1: !binary |-
    MjYzNWY1NTRmNjg5YWZlOWE3OWFhYjA3NTU2OWE3MzA4MDU0OGZhZg==
  fingerprint: !binary |-
    OGUwYjQ4Yzk1MDkzMGI4OTQ2NTkyZDlhYjAyZTFkOGExNmJjMmYxMA==
  dependencies:
  - golang
- name: nsync
  version: !binary |-
    ZTU2MGMyMWE4MDRmZmUxMDcyZmE3M2I2ZDExYzYzZjliM2IyODc2OQ==
  sha1: !binary |-
    OGRlZDZjZTEyYjE5MmEwNTNiMjRmM2E5NTlhOTNkNjUwZmM3NjFjNg==
  fingerprint: !binary |-
    ZTU2MGMyMWE4MDRmZmUxMDcyZmE3M2I2ZDExYzYzZjliM2IyODc2OQ==
  dependencies:
  - golang
- name: pid_utils
  version: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  sha1: !binary |-
    NzlmNmE4YmEzYTQzMTgxMTVmMzc1MDBkZThkZWE1OTAxNzU5MWQyOQ==
  fingerprint: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  dependencies: []
- name: etcd
  version: !binary |-
    YWNjZmNhODlkNDZjMjExOTBiZWRhMmJjNDIxNzdjZTcwZDg1ODRjMA==
  sha1: !binary |-
    YmVhODdiOTM1MmNmZGFkYjk0NzgxZTVhNDdjYjVjZGYyMzYxODUxMw==
  fingerprint: !binary |-
    YWNjZmNhODlkNDZjMjExOTBiZWRhMmJjNDIxNzdjZTcwZDg1ODRjMA==
  dependencies:
  - golang
- name: converger
  version: !binary |-
    MDM3OTM4OWEyNTJhZWNlZTIxYTYxZDA5NzA5YzM0MmNkYTE0NDllZA==
  sha1: !binary |-
    ZTlhYzU2M2JhOGFjNzEyZGVmYjllZmMzMWU5OWFjYTVkMjYxODczOA==
  fingerprint: !binary |-
    MDM3OTM4OWEyNTJhZWNlZTIxYTYxZDA5NzA5YzM0MmNkYTE0NDllZA==
  dependencies:
  - golang
- name: route_emitter
  version: !binary |-
    MmY4MWFmZjFiYTEwZmVjYWU0NTM1ZTY2YmM4M2E4YTczZWY1YzIzZQ==
  sha1: !binary |-
    Njk1ODg1YmQ3NjQyZjczNDIyYzNjZDUxMjIwMTg2YmY1MDE2NzYwZQ==
  fingerprint: !binary |-
    MmY4MWFmZjFiYTEwZmVjYWU0NTM1ZTY2YmM4M2E4YTczZWY1YzIzZQ==
  dependencies:
  - golang
- name: syslog_forwarder
  version: !binary |-
    OTVkZDcxNTI4NDU5YWU2MjFkZDhlODFhYzU5ZTViNWM4ZGE3NDdiNA==
  sha1: !binary |-
    ZmNjNzZjZjM1ZDUwMjRiOWU4NWU1YTdmZDA3MGM1ZTViOWFjNDAxNQ==
  fingerprint: !binary |-
    OTVkZDcxNTI4NDU5YWU2MjFkZDhlODFhYzU5ZTViNWM4ZGE3NDdiNA==
  dependencies: []
- name: docker-circus
  version: !binary |-
    MTkyYzk3Njg1Y2Q5NDdhMDIwYmJlOWUxOTcwMTRiNTYzZGRmMzg2Mw==
  sha1: !binary |-
    NDYyYzFiYTA1OGFjZjU3YzNhMzgyOWNiMWQ1MmIzNWFjZDJmNWIxMQ==
  fingerprint: !binary |-
    MTkyYzk3Njg1Y2Q5NDdhMDIwYmJlOWUxOTcwMTRiNTYzZGRmMzg2Mw==
  dependencies:
  - golang
- name: rootfs_lucid64
  version: !binary |-
    NzhmN2Y0NDI0N2IwYTJmN2ZkMDhmMmVjMWJkN2FiNmJiZjBkYmRkYw==
  sha1: !binary |-
    ZmVjY2MxY2E1OTVlODVhZWExMTU4OTM0ZTMwYzA1ZjQzYjIwZGNkZA==
  fingerprint: !binary |-
    NzhmN2Y0NDI0N2IwYTJmN2ZkMDhmMmVjMWJkN2FiNmJiZjBkYmRkYw==
  dependencies: []
- name: warden-linux
  version: !binary |-
    ZThjZDZhMDEwZTRhNGMxYmZjMzVmY2QyNjViOTVlMTMyOWJkYmE1YQ==
  sha1: !binary |-
    OTAyZTgwYWRmMTE0NzgzNGI2MjlmMjk4ZGU0MDEzMGI3ZTFlMWJkZA==
  fingerprint: !binary |-
    ZThjZDZhMDEwZTRhNGMxYmZjMzVmY2QyNjViOTVlMTMyOWJkYmE1YQ==
  dependencies:
  - golang
- name: file_server
  version: !binary |-
    ZWE5NDIwYWEwNWU3OTE2NmQ5Yjc5ZGZkZTcwODU2NDI1MmJiMTcxNg==
  sha1: !binary |-
    YjBkZmU0OTc5NDQ3YmQzYjg5MzA3ZDM5MjAzNjI4NTJmYjQ4YzNhZA==
  fingerprint: !binary |-
    ZWE5NDIwYWEwNWU3OTE2NmQ5Yjc5ZGZkZTcwODU2NDI1MmJiMTcxNg==
  dependencies:
  - golang
- name: auctioneer
  version: !binary |-
    ODJiNTYyMmIwYjA3NzU0ZDdkNTFmMWExYWI5YTZlODc2NGQ0ZDI5NA==
  sha1: !binary |-
    YjBlMjRiNGM3Y2NiNmRiMzNmNTZlODBmOWI1M2M0MDk2YmU3NWI1Nw==
  fingerprint: !binary |-
    ODJiNTYyMmIwYjA3NzU0ZDdkNTFmMWExYWI5YTZlODc2NGQ0ZDI5NA==
  dependencies:
  - golang
- name: executor
  version: !binary |-
    YjNkYmE3OWUwMmExMmQ4MmNjZWVmOTgxNWI0NjM5MzlhODQxYWY3ZQ==
  sha1: !binary |-
    ZWZmMDM4YzM5MTk5ZjhlNmMwYTJhZTcxOGU1MjY0MDc3OTFjZDdiNw==
  fingerprint: !binary |-
    YjNkYmE3OWUwMmExMmQ4MmNjZWVmOTgxNWI0NjM5MzlhODQxYWY3ZQ==
  dependencies:
  - golang
- name: runtime_metrics_server
  version: !binary |-
    MWZmY2YxMWY5NDg3NjM1MzAzZTgyY2RhYzhiY2U4OTZiZWJiM2M4YQ==
  sha1: !binary |-
    NjcwMjk1MTQ3MWZkNmQ1MWJlZjU0MjA1NDJkZjhmMzY0YTc3ZjY3Yw==
  fingerprint: !binary |-
    MWZmY2YxMWY5NDg3NjM1MzAzZTgyY2RhYzhiY2U4OTZiZWJiM2M4YQ==
  dependencies:
  - golang
- name: stager
  version: !binary |-
    ZGZjMzYzNWE1Y2NhZWFkM2JmMTZiMTQyMjUzODc2MDE4ZWE0NzAzZQ==
  sha1: !binary |-
    OTRhOGFhODIzMjgxMGI4ZDYwNDBjNmQzYjZhYzJlZTU5Yjg1MmFlNg==
  fingerprint: !binary |-
    ZGZjMzYzNWE1Y2NhZWFkM2JmMTZiMTQyMjUzODc2MDE4ZWE0NzAzZQ==
  dependencies:
  - golang
jobs:
- name: rep
  version: !binary |-
    ZDI2Nzc1ZTlhYzc3MWVkMzA5NjY5ZmVmMjcxZTY3OTE0NWVmNDg1Nw==
  fingerprint: !binary |-
    ZDI2Nzc1ZTlhYzc3MWVkMzA5NjY5ZmVmMjcxZTY3OTE0NWVmNDg1Nw==
  sha1: !binary |-
    YmFhNjYwZGFjMDQyZGE5YTJhNzkyYWNiNzIzYTRmNTdjYzY4Y2FkNw==
- name: etcd_metrics_server
  version: !binary |-
    Yzk1NGY3Mjk2YzM1ZGEzMWY5ZTc1YTA2Mjg5ZjQ4Y2Y1ZjAyMmE0YQ==
  fingerprint: !binary |-
    Yzk1NGY3Mjk2YzM1ZGEzMWY5ZTc1YTA2Mjg5ZjQ4Y2Y1ZjAyMmE0YQ==
  sha1: !binary |-
    NDdjM2YwZmI0OGVmNTMxY2EwYzg5ZmZkNTViOGNiZTliYjg0NDVjMQ==
- name: tps
  version: !binary |-
    OTgyYTUyYzI4Mjk0ODcxNzEzZDk5Mjg1MDYyNTk5NmU5MDhlZTllMg==
  fingerprint: !binary |-
    OTgyYTUyYzI4Mjk0ODcxNzEzZDk5Mjg1MDYyNTk5NmU5MDhlZTllMg==
  sha1: !binary |-
    MzdhZTRhN2Y2ZDZjY2U3ZDdlY2E1MzNiYTkzNTJhOTVkNmI1MjJhNw==
- name: nsync
  version: !binary |-
    NGU2OWMxYmI0ZTAxNzA3MGU2YTI0MDFmOWYxZGMxOTUwZTE2ZmVjOA==
  fingerprint: !binary |-
    NGU2OWMxYmI0ZTAxNzA3MGU2YTI0MDFmOWYxZGMxOTUwZTE2ZmVjOA==
  sha1: !binary |-
    NmEyMjFiZmFhN2Q5ODM5OGYyOGQxNzYxMjliZjExMThiODliM2U4Yg==
- name: etcd
  version: !binary |-
    Y2U2YTY4Y2I5YzEwYzFhNDhjMGIwYjFlMGQxZmU0ZDVmZTI1OTNiZg==
  fingerprint: !binary |-
    Y2U2YTY4Y2I5YzEwYzFhNDhjMGIwYjFlMGQxZmU0ZDVmZTI1OTNiZg==
  sha1: !binary |-
    MGJhYWI1NGNkZDc1ZjU4NDZmZDNiNTEwZDE4MmIyNWM4MGNiZjgyMw==
- name: converger
  version: !binary |-
    NjdkN2U4ZDQxMDc4MGY5MGE2MmNkY2M3OTUwZGJiODFmNTRlNWIxMw==
  fingerprint: !binary |-
    NjdkN2U4ZDQxMDc4MGY5MGE2MmNkY2M3OTUwZGJiODFmNTRlNWIxMw==
  sha1: !binary |-
    MzhjYzM0ZDI1MzEyODZlODlhMjFkNDhmNzMwYjYzOWIyZDEyZGNlZQ==
- name: route_emitter
  version: !binary |-
    Y2IxNzk3YzNkOWNhZTU5MDU1NWYwYmYwMTczYzE2NGI3Yzg0MjYwYQ==
  fingerprint: !binary |-
    Y2IxNzk3YzNkOWNhZTU5MDU1NWYwYmYwMTczYzE2NGI3Yzg0MjYwYQ==
  sha1: !binary |-
    YzI4NWIxNmZmZmRkZmIzZDg0ZWQyNGUzZTE5YTI0ZjVlMDlkZGY0Mg==
- name: warden
  version: !binary |-
    ZGM4NzRjZTJmNDgyNTQ1ZDNmZWRkZjJkMzgzYmU5YmJhZmQyNzEzYw==
  fingerprint: !binary |-
    ZGM4NzRjZTJmNDgyNTQ1ZDNmZWRkZjJkMzgzYmU5YmJhZmQyNzEzYw==
  sha1: !binary |-
    NTZlOWYyMjI2OWExN2VlNDYxYWRhNTFhNTM3ZjU3NzVmY2QwMjRlYw==
- name: file_server
  version: !binary |-
    N2I3YmM5YTRmZDkzMWZhMGViNGFlMDM4YzlhM2I0OTNhZTVjZDk2MQ==
  fingerprint: !binary |-
    N2I3YmM5YTRmZDkzMWZhMGViNGFlMDM4YzlhM2I0OTNhZTVjZDk2MQ==
  sha1: !binary |-
    YmZhYTA3OTU1MTIyZDY1NzJjMTlhZTMxZmUwMzQ0NWNkNGQ3OWEyYQ==
- name: auctioneer
  version: !binary |-
    ZDU5ZjJmOGY2YjAyYWIxN2ZiYTU1NWQ1YjdmMzk4YjE3NzVlMmVkMg==
  fingerprint: !binary |-
    ZDU5ZjJmOGY2YjAyYWIxN2ZiYTU1NWQ1YjdmMzk4YjE3NzVlMmVkMg==
  sha1: !binary |-
    NDYxNzY3YjExMjJhNDgxNTAwYjNhY2U3MDMxYzAwYTVjYmViMzFlMQ==
- name: executor
  version: !binary |-
    OGI5NWU4ZjcwZGQ4ODAyMmYwNWMwYjIxZjRlYmMxNzE0NTVlNDhiOA==
  fingerprint: !binary |-
    OGI5NWU4ZjcwZGQ4ODAyMmYwNWMwYjIxZjRlYmMxNzE0NTVlNDhiOA==
  sha1: !binary |-
    Y2EwOWQzN2VmMjFhZDFjMGE0NDY3YjUwY2JkZGUwMjgzOWMwNTc2OQ==
- name: runtime_metrics_server
  version: !binary |-
    OWFlNTk3NDZmN2E4YzIzMjYzMTFmYzgxOGU0OGYwOTc1ZDMyMzg0Mw==
  fingerprint: !binary |-
    OWFlNTk3NDZmN2E4YzIzMjYzMTFmYzgxOGU0OGYwOTc1ZDMyMzg0Mw==
  sha1: !binary |-
    MzFkYWEzZTQzYmMyOTdjN2Y3MGZmNGVhYmU5ZDY3ZWRkOWM1MGJkNQ==
- name: stager
  version: !binary |-
    NzhlODQyZGUzYzZhNjVmMzY3OTYwNjJiMjNkMjBiNjkyZjczZWU3Yw==
  fingerprint: !binary |-
    NzhlODQyZGUzYzZhNjVmMzY3OTYwNjJiMjNkMjBiNjkyZjczZWU3Yw==
  sha1: !binary |-
    MDgxMDhlMTVhYjc5OGNjN2NhNzlkYTdhZGE1OGMwYjA4NmViODliZQ==
commit_hash: bd7814e6
uncommitted_changes: true
name: diego
version: '0.280'
