---
packages:
- name: file_server
  version: !binary |-
    MTY5YjZkYWNiYzBjOWU5ZTQzZGI5OTQ5YWMyNjVlMDhmNGEwYmY2YQ==
  sha1: !binary |-
    OGZiMGQwNGY4M2I3YmMwNzdmMWNmMDE3NWFkMjIxNjhlNTY2N2M0ZA==
  fingerprint: !binary |-
    MTY5YjZkYWNiYzBjOWU5ZTQzZGI5OTQ5YWMyNjVlMDhmNGEwYmY2YQ==
  dependencies:
  - golang
- name: runtime_metrics_server
  version: !binary |-
    MWZmY2YxMWY5NDg3NjM1MzAzZTgyY2RhYzhiY2U4OTZiZWJiM2M4YQ==
  sha1: !binary |-
    NjcwMjk1MTQ3MWZkNmQ1MWJlZjU0MjA1NDJkZjhmMzY0YTc3ZjY3Yw==
  fingerprint: !binary |-
    MWZmY2YxMWY5NDg3NjM1MzAzZTgyY2RhYzhiY2U4OTZiZWJiM2M4YQ==
  dependencies:
  - golang
- name: docker-circus
  version: !binary |-
    OTlhZjU0YzA3ZjExYjk1NjFiOWRjZDM2NGEyMDBiZGIxYTgxMDg1ZQ==
  sha1: !binary |-
    YmUxMTVlOWVlOTg1Yjk3OTAxZmNjOTFjOGI3MDQxM2U3ZTQ0NjJhYg==
  fingerprint: !binary |-
    OTlhZjU0YzA3ZjExYjk1NjFiOWRjZDM2NGEyMDBiZGIxYTgxMDg1ZQ==
  dependencies:
  - golang
- name: etcd
  version: !binary |-
    YWNjZmNhODlkNDZjMjExOTBiZWRhMmJjNDIxNzdjZTcwZDg1ODRjMA==
  sha1: !binary |-
    YmVhODdiOTM1MmNmZGFkYjk0NzgxZTVhNDdjYjVjZGYyMzYxODUxMw==
  fingerprint: !binary |-
    YWNjZmNhODlkNDZjMjExOTBiZWRhMmJjNDIxNzdjZTcwZDg1ODRjMA==
  dependencies:
  - golang
- name: syslog_forwarder
  version: !binary |-
    OTVkZDcxNTI4NDU5YWU2MjFkZDhlODFhYzU5ZTViNWM4ZGE3NDdiNA==
  sha1: !binary |-
    ZmNjNzZjZjM1ZDUwMjRiOWU4NWU1YTdmZDA3MGM1ZTViOWFjNDAxNQ==
  fingerprint: !binary |-
    OTVkZDcxNTI4NDU5YWU2MjFkZDhlODFhYzU5ZTViNWM4ZGE3NDdiNA==
  dependencies: []
- name: route_emitter
  version: !binary |-
    MmY4MWFmZjFiYTEwZmVjYWU0NTM1ZTY2YmM4M2E4YTczZWY1YzIzZQ==
  sha1: !binary |-
    Njk1ODg1YmQ3NjQyZjczNDIyYzNjZDUxMjIwMTg2YmY1MDE2NzYwZQ==
  fingerprint: !binary |-
    MmY4MWFmZjFiYTEwZmVjYWU0NTM1ZTY2YmM4M2E4YTczZWY1YzIzZQ==
  dependencies:
  - golang
- name: rep
  version: !binary |-
    ZDc3MzIwMmM1MDIxMzRkMDMwZjY5NWNkNDE5YWY3MDI4ODNmYmUxYw==
  sha1: !binary |-
    ZjM0MTk1NDI5MWNiNmMxOTE2MDY1N2UwZGJlNzIzMGVmNjVhOTY4ZA==
  fingerprint: !binary |-
    ZDc3MzIwMmM1MDIxMzRkMDMwZjY5NWNkNDE5YWY3MDI4ODNmYmUxYw==
  dependencies:
  - golang
- name: warden-linux
  version: !binary |-
    NTJmNzZhMTU1OTY4MTFhYmU4NDVmMjA4NTk2YjdjY2VkMGI2YThkZg==
  sha1: !binary |-
    ODI3N2JlZGZiMmFkNGY5NTk2YTUyMGI0YjE2NWY5MTIyMjNmZjA0Yw==
  fingerprint: !binary |-
    NTJmNzZhMTU1OTY4MTFhYmU4NDVmMjA4NTk2YjdjY2VkMGI2YThkZg==
  dependencies:
  - golang
- name: linux-circus
  version: !binary |-
    ZTg5OTM0YzIyNmIxZDY4MDJjYjg0ZGE0OTg0ODM3NWU0MTM0MzI4MA==
  sha1: !binary |-
    NzdmYzBmMTkxY2Y5N2U5N2M4OWE1MjhkM2JhOTMwY2I0YTczMGQ2ZQ==
  fingerprint: !binary |-
    ZTg5OTM0YzIyNmIxZDY4MDJjYjg0ZGE0OTg0ODM3NWU0MTM0MzI4MA==
  dependencies:
  - golang
- name: golang
  version: !binary |-
    NTcyZDBjYTA5M2MzMTZhNmQxMDljNzIxZmYxOTdmYWQxM2YyMzI1NA==
  sha1: !binary |-
    NzJkNjFhYzY1NzI3YzgyNDllNWI0N2JjODlkY2ZhODRlOGYwYjEwNw==
  fingerprint: !binary |-
    NTcyZDBjYTA5M2MzMTZhNmQxMDljNzIxZmYxOTdmYWQxM2YyMzI1NA==
  dependencies: []
- name: tps
  version: !binary |-
    MWY2N2QzNWJlNTI2MDNlMjlhNTMwZmUzMjE5MGUyMTcwNDVlYTRmMA==
  sha1: !binary |-
    MTJkNDE4Y2VjZmQ1N2IxYThhNDYyODk4MTE5NGVmYTljZTE2ZWY3ZA==
  fingerprint: !binary |-
    MWY2N2QzNWJlNTI2MDNlMjlhNTMwZmUzMjE5MGUyMTcwNDVlYTRmMA==
  dependencies:
  - golang
- name: auctioneer
  version: !binary |-
    YjFkNmY1YTU1ODU0NDhkOTk5MzU1ZjFkYzI0ZDVkZmZiNGRlNDk5OA==
  sha1: !binary |-
    ZTQwYjBkMzFiYWNkYjVlOTQ3MzkyY2VjZDVkYTMxNGJiOTUwYjEzNw==
  fingerprint: !binary |-
    YjFkNmY1YTU1ODU0NDhkOTk5MzU1ZjFkYzI0ZDVkZmZiNGRlNDk5OA==
  dependencies:
  - golang
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    ODZhYjg4MmY4MTkxZjBjOGU2ZjVmYWVlYTBhOTE3M2MxMTkwZTA3ZQ==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  dependencies: []
- name: rootfs_lucid64
  version: !binary |-
    NzhmN2Y0NDI0N2IwYTJmN2ZkMDhmMmVjMWJkN2FiNmJiZjBkYmRkYw==
  sha1: !binary |-
    ZmVjY2MxY2E1OTVlODVhZWExMTU4OTM0ZTMwYzA1ZjQzYjIwZGNkZA==
  fingerprint: !binary |-
    NzhmN2Y0NDI0N2IwYTJmN2ZkMDhmMmVjMWJkN2FiNmJiZjBkYmRkYw==
  dependencies: []
- name: pid_utils
  version: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  sha1: !binary |-
    NzlmNmE4YmEzYTQzMTgxMTVmMzc1MDBkZThkZWE1OTAxNzU5MWQyOQ==
  fingerprint: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  dependencies: []
- name: nsync
  version: !binary |-
    MzBiZmQwMDMzNmJiYzllZDY2NTE3ZjMzMDIwZjliNTRlZDFiZjk4YQ==
  sha1: !binary |-
    M2IyNGRkNzI2N2RkYzg1MGNhNjJmNjQxMzNjZWNmMTQ0ZWU2NDlmNg==
  fingerprint: !binary |-
    MzBiZmQwMDMzNmJiYzllZDY2NTE3ZjMzMDIwZjliNTRlZDFiZjk4YQ==
  dependencies:
  - golang
- name: executor
  version: !binary |-
    ZmVjZDcwMjAzZDUwZjQ2YzQ5ZDQwNDZkMjliMTZhOWJlN2I0ZjdkZg==
  sha1: !binary |-
    Y2JkYjViZjAzYmQzODhhY2FkZjllYThjMGE3ZGEzZDRhMjFlNDRlZg==
  fingerprint: !binary |-
    ZmVjZDcwMjAzZDUwZjQ2YzQ5ZDQwNDZkMjliMTZhOWJlN2I0ZjdkZg==
  dependencies:
  - golang
- name: etcd_metrics_server
  version: !binary |-
    YzdhYTUyYWI5NzQwNWJjZjY2ZDhiYjQ1ZmQ3MDczMzI2OGE1MjcwYw==
  sha1: !binary |-
    YmYyYWM4ZmQ3YjY3M2QyZTk0Y2RmM2QwNjRmZmY5YTc4ZGE5YjAwYQ==
  fingerprint: !binary |-
    YzdhYTUyYWI5NzQwNWJjZjY2ZDhiYjQ1ZmQ3MDczMzI2OGE1MjcwYw==
  dependencies:
  - golang
- name: stager
  version: !binary |-
    ZGZjMzYzNWE1Y2NhZWFkM2JmMTZiMTQyMjUzODc2MDE4ZWE0NzAzZQ==
  sha1: !binary |-
    OTRhOGFhODIzMjgxMGI4ZDYwNDBjNmQzYjZhYzJlZTU5Yjg1MmFlNg==
  fingerprint: !binary |-
    ZGZjMzYzNWE1Y2NhZWFkM2JmMTZiMTQyMjUzODc2MDE4ZWE0NzAzZQ==
  dependencies:
  - golang
- name: converger
  version: !binary |-
    Zjc2NzUwY2RkNTFlNDdiMjU1MjU2MDc5Yjk5MjgyYTNkMjVkMzJiYw==
  sha1: !binary |-
    MTY3YjI4ZjE0OWJmYzg5NmJhZTZmMGJmNTZkNDFkYTAwODcwNTQzOA==
  fingerprint: !binary |-
    Zjc2NzUwY2RkNTFlNDdiMjU1MjU2MDc5Yjk5MjgyYTNkMjVkMzJiYw==
  dependencies:
  - golang
jobs:
- name: file_server
  version: !binary |-
    N2I3YmM5YTRmZDkzMWZhMGViNGFlMDM4YzlhM2I0OTNhZTVjZDk2MQ==
  fingerprint: !binary |-
    N2I3YmM5YTRmZDkzMWZhMGViNGFlMDM4YzlhM2I0OTNhZTVjZDk2MQ==
  sha1: !binary |-
    YmZhYTA3OTU1MTIyZDY1NzJjMTlhZTMxZmUwMzQ0NWNkNGQ3OWEyYQ==
- name: runtime_metrics_server
  version: !binary |-
    OWFlNTk3NDZmN2E4YzIzMjYzMTFmYzgxOGU0OGYwOTc1ZDMyMzg0Mw==
  fingerprint: !binary |-
    OWFlNTk3NDZmN2E4YzIzMjYzMTFmYzgxOGU0OGYwOTc1ZDMyMzg0Mw==
  sha1: !binary |-
    MzFkYWEzZTQzYmMyOTdjN2Y3MGZmNGVhYmU5ZDY3ZWRkOWM1MGJkNQ==
- name: etcd
  version: !binary |-
    Y2U2YTY4Y2I5YzEwYzFhNDhjMGIwYjFlMGQxZmU0ZDVmZTI1OTNiZg==
  fingerprint: !binary |-
    Y2U2YTY4Y2I5YzEwYzFhNDhjMGIwYjFlMGQxZmU0ZDVmZTI1OTNiZg==
  sha1: !binary |-
    MGJhYWI1NGNkZDc1ZjU4NDZmZDNiNTEwZDE4MmIyNWM4MGNiZjgyMw==
- name: warden
  version: !binary |-
    ZGM4NzRjZTJmNDgyNTQ1ZDNmZWRkZjJkMzgzYmU5YmJhZmQyNzEzYw==
  fingerprint: !binary |-
    ZGM4NzRjZTJmNDgyNTQ1ZDNmZWRkZjJkMzgzYmU5YmJhZmQyNzEzYw==
  sha1: !binary |-
    NTZlOWYyMjI2OWExN2VlNDYxYWRhNTFhNTM3ZjU3NzVmY2QwMjRlYw==
- name: route_emitter
  version: !binary |-
    Y2IxNzk3YzNkOWNhZTU5MDU1NWYwYmYwMTczYzE2NGI3Yzg0MjYwYQ==
  fingerprint: !binary |-
    Y2IxNzk3YzNkOWNhZTU5MDU1NWYwYmYwMTczYzE2NGI3Yzg0MjYwYQ==
  sha1: !binary |-
    YzI4NWIxNmZmZmRkZmIzZDg0ZWQyNGUzZTE5YTI0ZjVlMDlkZGY0Mg==
- name: rep
  version: !binary |-
    ZDI2Nzc1ZTlhYzc3MWVkMzA5NjY5ZmVmMjcxZTY3OTE0NWVmNDg1Nw==
  fingerprint: !binary |-
    ZDI2Nzc1ZTlhYzc3MWVkMzA5NjY5ZmVmMjcxZTY3OTE0NWVmNDg1Nw==
  sha1: !binary |-
    YmFhNjYwZGFjMDQyZGE5YTJhNzkyYWNiNzIzYTRmNTdjYzY4Y2FkNw==
- name: tps
  version: !binary |-
    OTgyYTUyYzI4Mjk0ODcxNzEzZDk5Mjg1MDYyNTk5NmU5MDhlZTllMg==
  fingerprint: !binary |-
    OTgyYTUyYzI4Mjk0ODcxNzEzZDk5Mjg1MDYyNTk5NmU5MDhlZTllMg==
  sha1: !binary |-
    MzdhZTRhN2Y2ZDZjY2U3ZDdlY2E1MzNiYTkzNTJhOTVkNmI1MjJhNw==
- name: auctioneer
  version: !binary |-
    ZDU5ZjJmOGY2YjAyYWIxN2ZiYTU1NWQ1YjdmMzk4YjE3NzVlMmVkMg==
  fingerprint: !binary |-
    ZDU5ZjJmOGY2YjAyYWIxN2ZiYTU1NWQ1YjdmMzk4YjE3NzVlMmVkMg==
  sha1: !binary |-
    NDYxNzY3YjExMjJhNDgxNTAwYjNhY2U3MDMxYzAwYTVjYmViMzFlMQ==
- name: nsync
  version: !binary |-
    NGU2OWMxYmI0ZTAxNzA3MGU2YTI0MDFmOWYxZGMxOTUwZTE2ZmVjOA==
  fingerprint: !binary |-
    NGU2OWMxYmI0ZTAxNzA3MGU2YTI0MDFmOWYxZGMxOTUwZTE2ZmVjOA==
  sha1: !binary |-
    NmEyMjFiZmFhN2Q5ODM5OGYyOGQxNzYxMjliZjExMThiODliM2U4Yg==
- name: executor
  version: !binary |-
    OGI5NWU4ZjcwZGQ4ODAyMmYwNWMwYjIxZjRlYmMxNzE0NTVlNDhiOA==
  fingerprint: !binary |-
    OGI5NWU4ZjcwZGQ4ODAyMmYwNWMwYjIxZjRlYmMxNzE0NTVlNDhiOA==
  sha1: !binary |-
    Y2EwOWQzN2VmMjFhZDFjMGE0NDY3YjUwY2JkZGUwMjgzOWMwNTc2OQ==
- name: etcd_metrics_server
  version: !binary |-
    Yzk1NGY3Mjk2YzM1ZGEzMWY5ZTc1YTA2Mjg5ZjQ4Y2Y1ZjAyMmE0YQ==
  fingerprint: !binary |-
    Yzk1NGY3Mjk2YzM1ZGEzMWY5ZTc1YTA2Mjg5ZjQ4Y2Y1ZjAyMmE0YQ==
  sha1: !binary |-
    NDdjM2YwZmI0OGVmNTMxY2EwYzg5ZmZkNTViOGNiZTliYjg0NDVjMQ==
- name: stager
  version: !binary |-
    NzhlODQyZGUzYzZhNjVmMzY3OTYwNjJiMjNkMjBiNjkyZjczZWU3Yw==
  fingerprint: !binary |-
    NzhlODQyZGUzYzZhNjVmMzY3OTYwNjJiMjNkMjBiNjkyZjczZWU3Yw==
  sha1: !binary |-
    MDgxMDhlMTVhYjc5OGNjN2NhNzlkYTdhZGE1OGMwYjA4NmViODliZQ==
- name: converger
  version: !binary |-
    NjdkN2U4ZDQxMDc4MGY5MGE2MmNkY2M3OTUwZGJiODFmNTRlNWIxMw==
  fingerprint: !binary |-
    NjdkN2U4ZDQxMDc4MGY5MGE2MmNkY2M3OTUwZGJiODFmNTRlNWIxMw==
  sha1: !binary |-
    MzhjYzM0ZDI1MzEyODZlODlhMjFkNDhmNzMwYjYzOWIyZDEyZGNlZQ==
commit_hash: 6abd21f3
uncommitted_changes: true
name: diego
version: '0.265'
