---
packages:
- name: etcd_metrics_server
  version: !binary |-
    NWQ3ZmY5NGM1MTk3NzhmN2U0MjBiNGU4OWU5MGNhMmMyM2E5M2ZiYQ==
  sha1: !binary |-
    N2M2NjVhZjVmNTFjMTA3NTc4OTg0YzZiMTM1YmNhNGViMjVlODVmYg==
  fingerprint: !binary |-
    NWQ3ZmY5NGM1MTk3NzhmN2U0MjBiNGU4OWU5MGNhMmMyM2E5M2ZiYQ==
  dependencies:
  - golang
- name: pid_utils
  version: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  sha1: !binary |-
    NzlmNmE4YmEzYTQzMTgxMTVmMzc1MDBkZThkZWE1OTAxNzU5MWQyOQ==
  fingerprint: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  dependencies: []
- name: runtime_metrics_server
  version: !binary |-
    ZDA4NTY4NzE0MmE5ZGJjZDc2OGNiNGU0YjMzMDhmYjYxM2QxYTJlZg==
  sha1: !binary |-
    MjVhNjQwN2Y3Yzk0ODc3ZWJjOTI4NjcyYjAwOTMwYTYwZmYwM2Y0NA==
  fingerprint: !binary |-
    ZDA4NTY4NzE0MmE5ZGJjZDc2OGNiNGU0YjMzMDhmYjYxM2QxYTJlZg==
  dependencies:
  - golang
- name: etcd
  version: !binary |-
    YWNjZmNhODlkNDZjMjExOTBiZWRhMmJjNDIxNzdjZTcwZDg1ODRjMA==
  sha1: !binary |-
    YmVhODdiOTM1MmNmZGFkYjk0NzgxZTVhNDdjYjVjZGYyMzYxODUxMw==
  fingerprint: !binary |-
    YWNjZmNhODlkNDZjMjExOTBiZWRhMmJjNDIxNzdjZTcwZDg1ODRjMA==
  dependencies:
  - golang
- name: linux-circus
  version: !binary |-
    ZmRlZjY4OTk0ZDY2MGJmOTcwYTQ0ZmI2YWE2NTRhNzA1ZWQ5MWQwZA==
  sha1: !binary |-
    ZjUxMTNkZTFlYzZkYWI1ZDhkZTkyNDQxNWEwNDkzMzQ0OTZjYjNkYg==
  fingerprint: !binary |-
    ZmRlZjY4OTk0ZDY2MGJmOTcwYTQ0ZmI2YWE2NTRhNzA1ZWQ5MWQwZA==
  dependencies:
  - golang
- name: warden-linux
  version: !binary |-
    Nzc1NmNlYzVhZDIxNTY1YTIwZTA5NzA2ZTY4MGJmN2MyNDU4MDM1MQ==
  sha1: !binary |-
    N2NjMDg5MDNhOGMwMWZmOTM5MTAyYThhM2QxMDEzMjFlZTNiMTZmZg==
  fingerprint: !binary |-
    Nzc1NmNlYzVhZDIxNTY1YTIwZTA5NzA2ZTY4MGJmN2MyNDU4MDM1MQ==
  dependencies:
  - golang
- name: shadow
  version: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  sha1: !binary |-
    MjFlNDkxOTliYTQ5Yjk4ZjY3YTZmOTUyZTM1NzMwZDZhZTZkY2RiZg==
  fingerprint: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  dependencies: []
- name: file_server
  version: !binary |-
    NGNmMTdlMWRjNTBkNGY4NjBkODBmYTljYjgxMDA2ZjRlODMzNDc2Yw==
  sha1: !binary |-
    NmQ4ZGE4MGE2ODhjYzMyZDA0ODRkMjg4Yjg3ZjczOWVjMjE1OTVlOA==
  fingerprint: !binary |-
    NGNmMTdlMWRjNTBkNGY4NjBkODBmYTljYjgxMDA2ZjRlODMzNDc2Yw==
  dependencies:
  - golang
- name: route_emitter
  version: !binary |-
    Y2EzZTdkYzA1OTI1MzhkNmY0ZWJhMDE4OGY4NzFjODBkZDI1YmU1NQ==
  sha1: !binary |-
    OGQ5ODRmYmE5NzFkODI2MzI1NGVmY2Q2ZjYxMmEzNThjNjViMGUxZA==
  fingerprint: !binary |-
    Y2EzZTdkYzA1OTI1MzhkNmY0ZWJhMDE4OGY4NzFjODBkZDI1YmU1NQ==
  dependencies:
  - golang
- name: auctioneer
  version: !binary |-
    YTNhNWU0NjkxZTk5NzkyY2IzNzBhZjhjYmQwNDc4MmU5MDc5MDU2Mg==
  sha1: !binary |-
    Y2FlZWE3ZTY3YmUyZWQ5YTAxODdhYTg5YmQwZTkyMzc1NThkMmJjZg==
  fingerprint: !binary |-
    YTNhNWU0NjkxZTk5NzkyY2IzNzBhZjhjYmQwNDc4MmU5MDc5MDU2Mg==
  dependencies:
  - golang
- name: stager
  version: !binary |-
    OTNkNjRkMjY1MjM3N2ZhNGViODFlNjk1MzQzNmRkMmQ3MTcyNjc4Yg==
  sha1: !binary |-
    NGQyZGUwOGVlYTVhMTBiZGFiNmYzOTUyYjY0YTJlODJmNDA2Yzk0ZA==
  fingerprint: !binary |-
    OTNkNjRkMjY1MjM3N2ZhNGViODFlNjk1MzQzNmRkMmQ3MTcyNjc4Yg==
  dependencies:
  - golang
- name: executor
  version: !binary |-
    ZWU3NjBhZjZiYjhjYTA1NGZjYzRmYTVkNDM4MGZiZDVhNTMwYmZhMg==
  sha1: !binary |-
    NDAyMGE3YTkwM2Q1OWViYTk4NDE0ZDkzMjRhYzExZjVlNjQ0MjRkZA==
  fingerprint: !binary |-
    ZWU3NjBhZjZiYjhjYTA1NGZjYzRmYTVkNDM4MGZiZDVhNTMwYmZhMg==
  dependencies:
  - golang
- name: rootfs_lucid64
  version: !binary |-
    NzhmN2Y0NDI0N2IwYTJmN2ZkMDhmMmVjMWJkN2FiNmJiZjBkYmRkYw==
  sha1: !binary |-
    ZmVjY2MxY2E1OTVlODVhZWExMTU4OTM0ZTMwYzA1ZjQzYjIwZGNkZA==
  fingerprint: !binary |-
    NzhmN2Y0NDI0N2IwYTJmN2ZkMDhmMmVjMWJkN2FiNmJiZjBkYmRkYw==
  dependencies: []
- name: converger
  version: !binary |-
    ZmZlMzIyZTM5MzhjZDI5YzYwYjU5OWQ2ZTdkZGJlN2U5N2Y1NWFiZg==
  sha1: !binary |-
    YjNjN2M0NzZkNzc3N2JjNThiNDlmYWNmNmExYTRmYmExNTY2ZGRjNw==
  fingerprint: !binary |-
    ZmZlMzIyZTM5MzhjZDI5YzYwYjU5OWQ2ZTdkZGJlN2U5N2Y1NWFiZg==
  dependencies:
  - golang
- name: rep
  version: !binary |-
    NTQ3MzUyOWRlNWQ0NzE2MjYxM2RiZDc5MzEwNjE0NDRlMmVmNDBhZA==
  sha1: !binary |-
    ODE4NDA4ZjE0MGQzZmMyZjUyZmU3YmQ1ZjY3YThkM2FjYWM3ZjU5Yw==
  fingerprint: !binary |-
    NTQ3MzUyOWRlNWQ0NzE2MjYxM2RiZDc5MzEwNjE0NDRlMmVmNDBhZA==
  dependencies:
  - golang
- name: nsync
  version: !binary |-
    MjE1NTMyYjllY2NmZTI2OTA5YjFmNjVlMDEzNzExOWFjYTJlYjZiNA==
  sha1: !binary |-
    ZTE4ODlkM2VjNzQwNGZhOGIwNjlmOGY4YWRiMzZmZTE0YzQyNDFkMw==
  fingerprint: !binary |-
    MjE1NTMyYjllY2NmZTI2OTA5YjFmNjVlMDEzNzExOWFjYTJlYjZiNA==
  dependencies:
  - golang
- name: syslog_forwarder
  version: !binary |-
    OTVkZDcxNTI4NDU5YWU2MjFkZDhlODFhYzU5ZTViNWM4ZGE3NDdiNA==
  sha1: !binary |-
    ZmNjNzZjZjM1ZDUwMjRiOWU4NWU1YTdmZDA3MGM1ZTViOWFjNDAxNQ==
  fingerprint: !binary |-
    OTVkZDcxNTI4NDU5YWU2MjFkZDhlODFhYzU5ZTViNWM4ZGE3NDdiNA==
  dependencies: []
- name: docker-circus
  version: !binary |-
    ODZjZTdjZTM4ODI3ODhlNzhkM2U2ZTA3Zjc1ZGQyMTcxNTZhOWQ3YQ==
  sha1: !binary |-
    NmZkYjFjYmRmMDhmMWYxZWQzZDk2ODQ2NzE2NzIyZjAzZTAzM2JjOA==
  fingerprint: !binary |-
    ODZjZTdjZTM4ODI3ODhlNzhkM2U2ZTA3Zjc1ZGQyMTcxNTZhOWQ3YQ==
  dependencies:
  - golang
- name: golang
  version: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  sha1: !binary |-
    ZDBlMDA5MmU5MDZmNTY1YzYxMTNkNzk1MGExZDU0YTk5MWRmYjM4Mg==
  fingerprint: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  dependencies: []
- name: tps
  version: !binary |-
    YjIzN2M2NzRmOGIwMzJiNjI5ZGIwYjJhMDNlYjgxNzhiNDg5ZTBlZg==
  sha1: !binary |-
    NzU2MWNmOTg2OGI1ZWI0NzkzNjg0ZjdlZjRhMWNkMzhmNzUxOGU2Mw==
  fingerprint: !binary |-
    YjIzN2M2NzRmOGIwMzJiNjI5ZGIwYjJhMDNlYjgxNzhiNDg5ZTBlZg==
  dependencies:
  - golang
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    ODZhYjg4MmY4MTkxZjBjOGU2ZjVmYWVlYTBhOTE3M2MxMTkwZTA3ZQ==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  dependencies: []
jobs:
- name: etcd_metrics_server
  version: !binary |-
    Yzk1NGY3Mjk2YzM1ZGEzMWY5ZTc1YTA2Mjg5ZjQ4Y2Y1ZjAyMmE0YQ==
  fingerprint: !binary |-
    Yzk1NGY3Mjk2YzM1ZGEzMWY5ZTc1YTA2Mjg5ZjQ4Y2Y1ZjAyMmE0YQ==
  sha1: !binary |-
    NDdjM2YwZmI0OGVmNTMxY2EwYzg5ZmZkNTViOGNiZTliYjg0NDVjMQ==
- name: runtime_metrics_server
  version: !binary |-
    OWFlNTk3NDZmN2E4YzIzMjYzMTFmYzgxOGU0OGYwOTc1ZDMyMzg0Mw==
  fingerprint: !binary |-
    OWFlNTk3NDZmN2E4YzIzMjYzMTFmYzgxOGU0OGYwOTc1ZDMyMzg0Mw==
  sha1: !binary |-
    MzFkYWEzZTQzYmMyOTdjN2Y3MGZmNGVhYmU5ZDY3ZWRkOWM1MGJkNQ==
- name: etcd
  version: !binary |-
    Y2U2YTY4Y2I5YzEwYzFhNDhjMGIwYjFlMGQxZmU0ZDVmZTI1OTNiZg==
  fingerprint: !binary |-
    Y2U2YTY4Y2I5YzEwYzFhNDhjMGIwYjFlMGQxZmU0ZDVmZTI1OTNiZg==
  sha1: !binary |-
    MGJhYWI1NGNkZDc1ZjU4NDZmZDNiNTEwZDE4MmIyNWM4MGNiZjgyMw==
- name: file_server
  version: !binary |-
    NmNiZDFiZmUyNjk1OGZlMzk0MzY1ZmZkODY4YTU3YzZjOTFhNjcwOA==
  fingerprint: !binary |-
    NmNiZDFiZmUyNjk1OGZlMzk0MzY1ZmZkODY4YTU3YzZjOTFhNjcwOA==
  sha1: !binary |-
    ZTUwZGRhNjk3ZTFiODk0NmYzYTFiYzY5YmIyMTE3YmI5NzVhNTRkYQ==
- name: route_emitter
  version: !binary |-
    Y2IxNzk3YzNkOWNhZTU5MDU1NWYwYmYwMTczYzE2NGI3Yzg0MjYwYQ==
  fingerprint: !binary |-
    Y2IxNzk3YzNkOWNhZTU5MDU1NWYwYmYwMTczYzE2NGI3Yzg0MjYwYQ==
  sha1: !binary |-
    YzI4NWIxNmZmZmRkZmIzZDg0ZWQyNGUzZTE5YTI0ZjVlMDlkZGY0Mg==
- name: auctioneer
  version: !binary |-
    NDQ5ZGExZGVkZmU4YzFhN2JjOTFjNjhhMGYwM2M1MDI2MDdiOGMxNg==
  fingerprint: !binary |-
    NDQ5ZGExZGVkZmU4YzFhN2JjOTFjNjhhMGYwM2M1MDI2MDdiOGMxNg==
  sha1: !binary |-
    MjYyZTU1MWI4Y2Q3ZDZkMjc0NjJlYTRiNzNkMTkwYjdiMmIyZDNiYw==
- name: stager
  version: !binary |-
    NzhlODQyZGUzYzZhNjVmMzY3OTYwNjJiMjNkMjBiNjkyZjczZWU3Yw==
  fingerprint: !binary |-
    NzhlODQyZGUzYzZhNjVmMzY3OTYwNjJiMjNkMjBiNjkyZjczZWU3Yw==
  sha1: !binary |-
    MDgxMDhlMTVhYjc5OGNjN2NhNzlkYTdhZGE1OGMwYjA4NmViODliZQ==
- name: executor
  version: !binary |-
    MTE5OGYzMGJjNzk4M2U3MWVmNGIxODc4ODU5Y2ZlM2UyOTY1Mzk4ZQ==
  fingerprint: !binary |-
    MTE5OGYzMGJjNzk4M2U3MWVmNGIxODc4ODU5Y2ZlM2UyOTY1Mzk4ZQ==
  sha1: !binary |-
    NDYwYzZmOWJhNWMzOTJiMzNiZjU2NmE5OGI3OTMxOTdmNmMxMGIxNg==
- name: converger
  version: !binary |-
    M2M3MDAwNDNjNTlkNzBjMzlmZDkzOTVmODczMGNhYWVlNWFjMzY3OQ==
  fingerprint: !binary |-
    M2M3MDAwNDNjNTlkNzBjMzlmZDkzOTVmODczMGNhYWVlNWFjMzY3OQ==
  sha1: !binary |-
    MDcwZjVlM2E2ZDZiMjNjM2IxNjI3N2QxYmViYWU0ZjNhYmFmM2Y3YQ==
- name: rep
  version: !binary |-
    NjNmYjU0ZjA4Yzg0MDEyZDg2MjJmYzA0Njk3MTZhNjI5NDdhMjU1Mg==
  fingerprint: !binary |-
    NjNmYjU0ZjA4Yzg0MDEyZDg2MjJmYzA0Njk3MTZhNjI5NDdhMjU1Mg==
  sha1: !binary |-
    NGM2YmEyYWY0ZDYzMmFiYzhkOTRlM2EyZDQ1NzUxYWJlMjhiMDA4Nw==
- name: nsync
  version: !binary |-
    NGU2OWMxYmI0ZTAxNzA3MGU2YTI0MDFmOWYxZGMxOTUwZTE2ZmVjOA==
  fingerprint: !binary |-
    NGU2OWMxYmI0ZTAxNzA3MGU2YTI0MDFmOWYxZGMxOTUwZTE2ZmVjOA==
  sha1: !binary |-
    NmEyMjFiZmFhN2Q5ODM5OGYyOGQxNzYxMjliZjExMThiODliM2U4Yg==
- name: tps
  version: !binary |-
    OTgyYTUyYzI4Mjk0ODcxNzEzZDk5Mjg1MDYyNTk5NmU5MDhlZTllMg==
  fingerprint: !binary |-
    OTgyYTUyYzI4Mjk0ODcxNzEzZDk5Mjg1MDYyNTk5NmU5MDhlZTllMg==
  sha1: !binary |-
    MzdhZTRhN2Y2ZDZjY2U3ZDdlY2E1MzNiYTkzNTJhOTVkNmI1MjJhNw==
- name: warden
  version: !binary |-
    Zjg4OGVjYTViNzhhNWUwOWM0MzU5NzIyYmExMmI2MjNhMjkzMWNlNw==
  fingerprint: !binary |-
    Zjg4OGVjYTViNzhhNWUwOWM0MzU5NzIyYmExMmI2MjNhMjkzMWNlNw==
  sha1: !binary |-
    ZmM3YWIxNWU3NTFjY2RiNDU2NjBiZmY0YWM4NmNmMTczYmY1YzE4ZA==
commit_hash: b43bf2c4
uncommitted_changes: true
name: diego
version: '0.322'
