meta: (( merge ))

networks: (( merge ))

releases:
  - name: diego
    version: latest
  - name: cf
    version: latest

external_services: (( merge ))

jobs:
  - name: cell_z1
    release: diego
    templates:
      - name: executor
      - name: converger
      - name: rep
      - name: auctioneer
      - name: warden
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: large_z1
    networks:
      - name: diego1
    properties:
      network_name: diego1
      loggregator_endpoint:
        shared_secret: (( external_services.loggregator_endpoint.z1.shared_secret ))
      nats: (( external_services.nats ))
      metron_agent:
        zone: z1

  - name: cell_z2
    release: diego
    templates:
      - name: executor
      - name: converger
      - name: rep
      - name: auctioneer
      - name: warden
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: large_z2
    networks:
      - name: diego2
    properties:
      network_name: diego2
      loggregator_endpoint:
        shared_secret: (( external_services.loggregator_endpoint.z2.shared_secret ))
      nats: (( external_services.nats ))
      metron_agent:
        zone: z2

  - name: file_server_z1
    release: diego
    templates:
      - name: file_server
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: small_z1
    networks:
      - name: diego1
    properties:
      network_name: diego1
      cc: (( external_services.cc ))
      nats: (( external_services.nats ))
      loggregator_endpoint:
        shared_secret: (( external_services.loggregator_endpoint.z1.shared_secret ))
      metron_agent:
        zone: z1

  - name: file_server_z2
    release: diego
    templates:
      - name: file_server
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: small_z2
    networks:
      - name: diego2
    properties:
      network_name: diego2
      cc: (( external_services.cc ))
      nats: (( external_services.nats ))
      loggregator_endpoint:
        shared_secret: (( external_services.loggregator_endpoint.z2.shared_secret ))
      metron_agent:
        zone: z2

  - name: cc_bridge_z1
    release: diego
    templates:
      - name: stager
      - name: nsync
      - name: tps
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: small_z1
    networks:
      - name: diego1
    properties:
      network_name: diego1
      nats: (( external_services.nats ))
      loggregator_endpoint:
        shared_secret: (( external_services.loggregator_endpoint.z1.shared_secret ))
      metron_agent:
        zone: z1

  - name: cc_bridge_z2
    release: diego
    templates:
      - name: stager
      - name: nsync
      - name: tps
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: small_z2
    networks:
      - name: diego2
    properties:
      network_name: diego2
      nats: (( external_services.nats ))
      loggregator_endpoint:
        shared_secret: (( external_services.loggregator_endpoint.z2.shared_secret ))
      metron_agent:
        zone: z2

  - name: route_emitter_z1
    release: diego
    templates:
      - name: route_emitter
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: small_z1
    networks:
      - name: diego1
    properties:
      network_name: diego1
      nats: (( external_services.nats ))
      loggregator_endpoint:
        shared_secret: (( external_services.loggregator_endpoint.z1.shared_secret ))
      metron_agent:
        zone: z1

  - name: route_emitter_z2
    release: diego
    templates:
      - name: route_emitter
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: small_z2
    networks:
      - name: diego2
    properties:
      network_name: diego2
      nats: (( external_services.nats ))
      loggregator_endpoint:
        shared_secret: (( external_services.loggregator_endpoint.z2.shared_secret ))
      metron_agent:
        zone: z2

  - name: runtime_metrics_server_z1
    release: diego
    templates:
      - name: runtime_metrics_server
      - name: metron_agent
        release: cf
    instances: 1
    resource_pool: small_z1
    networks:
      - name: diego1
    properties:
      network_name: diego1
      nats: (( external_services.nats ))
      loggregator_endpoint:
        shared_secret: (( external_services.loggregator_endpoint.z1.shared_secret ))
      metron_agent:
        zone: z1

  - name: etcd_z1
    release: diego
    templates:
      - name: etcd
      - name: etcd_metrics_server
    instances: 1
    resource_pool: medium_z1
    networks:
      - name: diego1
        static_ips: (( merge ))
    properties:
      network_name: diego1
    update:
      serial: true

  - name: etcd_z2
    release: diego
    templates:
      - name: etcd
      - name: etcd_metrics_server
    instances: 1
    resource_pool: medium_z2
    networks:
      - name: diego2
        static_ips: (( merge ))
    properties:
      network_name: diego2
    update:
      serial: true

  - name: etcd_z3
    release: diego
    templates:
      - name: etcd
      - name: etcd_metrics_server
    instances: 1
    resource_pool: medium_z3
    networks:
      - name: diego3
        static_ips: (( merge ))
    properties:
      network_name: diego3
    update:
      serial: true

  - name: acceptance_tests_diego
    release: cf
    templates:
    - name: acceptance-tests
    instances: 0
    resource_pool: small_errand
    lifecycle: errand
    networks:
      - name: diego1
    properties:
      acceptance_tests:
        diego: true

properties:
  diego:
    etcd:
      machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))

  etcd: # IMPORTANT: metron_agent from cf-release uses top-level etcd property
    machines: (( external_services.cf_etcd.machines ))

  ssl:
    skip_cert_verify: false

  warden: ~

  stager:
    lifecycle_bundles: ~

  executor:
    drain_timeout: ~
    warden: ~

  syslog_aggregator: ~

  rep:
    etcd:
      machines: (( .properties.diego.etcd.machines ))

    nats:
      machines: (( external_services.nats.machines ))
      username: (( external_services.nats.user ))
      password: (( external_services.nats.password ))

  converger:
    etcd:
      machines: (( .properties.diego.etcd.machines ))

  auctioneer:
    etcd:
      machines: (( .properties.diego.etcd.machines ))

    nats:
      machines: (( external_services.nats.machines ))
      username: (( external_services.nats.user ))
      password: (( external_services.nats.password ))

  route_emitter:
    etcd:
      machines: (( .properties.diego.etcd.machines ))

    nats:
      machines: (( external_services.nats.machines ))
      username: (( external_services.nats.user ))
      password: (( external_services.nats.password ))

  etcd_metrics_server:
    job_name: "etcd-diego"
    nats:
      machines: (( external_services.nats.machines ))
      username: (( external_services.nats.user ))
      password: (( external_services.nats.password ))

  file_server:
      etcd:
        machines: (( .properties.diego.etcd.machines ))
  
  nsync:
    etcd:
      machines: (( .properties.diego.etcd.machines ))
    lifecycle_bundles: ~
    cc:
      base_url: (( external_services.cc.srv_api_uri ))
      basic_auth_password: (( external_services.cc.bulk_api_password ))

  runtime_metrics_server:
    etcd:
      machines: (( .properties.diego.etcd.machines ))

    nats:
      machines: (( external_services.nats.machines ))
      username: (( external_services.nats.user ))
      password: (( external_services.nats.password ))

  stager:
    etcd:
      machines: (( .properties.diego.etcd.machines ))

  tps:
    etcd:
      machines: (( .properties.diego.etcd.machines ))

  acceptance_tests: (( merge || nil ))
