meta: (( merge ))

networks: (( merge ))

releases:
  - name: diego
    version: latest

external_services: (( merge ))

jobs:
  - name: executor_z1
    release: diego
    template:
      - executor
      - warden
    instances: 1
    resource_pool: large_z1
    networks:
      - name: diego1
    properties:
      network_name: diego1
      loggregator_endpoint: (( external_services.loggregator_endpoint.z1 ))

  - name: executor_z2
    release: diego
    template:
      - executor
      - warden
    instances: 1
    resource_pool: large_z2
    networks:
      - name: diego2
    properties:
      network_name: diego2
      loggregator_endpoint: (( external_services.loggregator_endpoint.z2 ))

  - name: file_server_z1
    release: diego
    template:
      - file_server
    instances: 1
    resource_pool: small_z1
    networks:
      - name: diego1
    properties:
      network_name: diego1

  - name: file_server_z2
    release: diego
    template:
      - file_server
    instances: 1
    resource_pool: small_z2
    networks:
      - name: diego2
    properties:
      network_name: diego2

  - name: stager_z1
    release: diego
    template:
      - stager
    instances: 1
    resource_pool: small_z1
    networks:
      - name: diego1
    properties:
      network_name: diego1

  - name: stager_z2
    release: diego
    template:
      - stager
    instances: 1
    resource_pool: small_z2
    networks:
      - name: diego2
    properties:
      network_name: diego2

  - name: runtime_metrics_server_z1
    release: diego
    template:
      - runtime_metrics_server
    instances: 1
    resource_pool: small_z1
    networks:
      - name: diego1
    properties:
      network_name: diego1

  - name: etcd_z1
    release: diego
    template:
      - etcd
    instances: 1
    resource_pool: medium_z1
    networks:
      - name: diego1
        static_ips: (( merge ))
    properties:
      network_name: diego1

  - name: etcd_z2
    release: diego
    template:
      - etcd
    instances: 1
    resource_pool: medium_z2
    networks:
      - name: diego2
        static_ips: (( merge ))
    properties:
      network_name: diego2

  - name: etcd_z3
    release: diego
    template:
      - etcd
    instances: 1
    resource_pool: medium_z3
    networks:
      - name: diego3
        static_ips: (( merge ))
    properties:
      network_name: diego3

properties:
  <<: (( merge || nil ))

  warden: ~

  executor:
    memory_capacity_mb: 1024
    disk_capacity_mb: 10240
    container_inode_limit: 200000
    stack: "lucid64"
    warden: ~

  stager:
    compilers:
      lucid64: linux-smelter/linux-smelter.zip

  etcd:
    machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))

  nats: (( external_services.nats ))
  cc: (( external_services.cc ))

  runtime_metrics_server:
    etcd:
      machines: (( .properties.etcd.machines ))

    nats:
      machines: (( .properties.nats.machines ))
      username: (( .properties.nats.user ))
      password: (( .properties.nats.password ))
