meta: (( merge ))

networks: (( merge ))

releases:
  - name: diego
    version: latest
  - name: cf
    version: latest

jobs:
  - <<: (( merge || nil ))

  - name: executor_z1
    release: diego
    template:
      - warden
      - executor
    instances: 1
    resource_pool: large_z1
    networks:
      - name: cf1
    properties:
      network_name: cf1
      loggregator_endpoint: (( meta.loggregator_endpoint.z1 ))

  - name: executor_z2
    release: diego
    template:
      - warden
      - executor
    instances: 1
    resource_pool: large_z2
    networks:
      - name: cf2
    properties:
      network_name: cf2
      loggregator_endpoint: (( meta.loggregator_endpoint.z2 ))

  - name: file-server_z1
    release: diego
    template:
      - file-server
    instances: 1
    resource_pool: small_z1
    networks:
      - name: cf1
    properties:
      network_name: cf1

  - name: file-server_z2
    release: diego
    template:
      - file-server
    instances: 1
    resource_pool: small_z2
    networks:
      - name: cf2
    properties:
      network_name: cf2

  - name: stager_z1
    release: diego
    template:
      - stager
    instances: 1
    resource_pool: small_z1
    networks:
      - name: cf1
    properties:
      network_name: cf1

  - name: stager_z2
    release: diego
    template:
      - stager
    instances: 1
    resource_pool: small_z2
    networks:
      - name: cf2
    properties:
      network_name: cf2

properties:
  <<: (( merge || nil ))

  warden: ~

  executor:
    memory_capacity_mb: 1024
    disk_capacity_mb: 10240
    container_inode_limit: 200000
    stack: "lucid64"

  stager:
    compilers:
      lucid64: linux-smelter/linux-smelter.zip

  etcd:
    machines: (( jobs.etcd_leader_z1.networks.cf1.static_ips jobs.etcd_z1.networks.cf1.static_ips jobs.etcd_z2.networks.cf2.static_ips ))
