director_uuid: (( merge ))

meta:
  smoke_tests:
    api: (( merge ))
    skip_ssl_validation: (( merge ))
    username: (( merge ))
    password: (( merge ))
    organization: (( merge ))
    space: (( merge ))

    infrastructure:
      subnet: (( merge ))
      security_group: (( merge ))
      availability_zone: (( merge ))

name: diego-smoke-tests

releases:
  - name: diego
    version: latest

networks:
  - name: default
    type: dynamic
    cloud_properties:
      subnet: (( meta.smoke_tests.infrastructure.subnet ))
      security_groups:
        - (( meta.smoke_tests.infrastructure.security_group ))

resource_pools:
  - name: small_errand
    network: default
    stemcell:
      name: bosh-aws-xen-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      availability_zone: (( meta.smoke_tests.infrastructure.availability_zone ))
      instance_type: m3.medium

compilation:
  network: default
  workers: 6
  reuse_compilation_vms: true
  cloud_properties:
    availability_zone: (( meta.smoke_tests.infrastructure.availability_zone ))
    instance_type: c1.medium

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

jobs:
- name: diego_smoke_tests
  templates:
    - name: smoke-tests
      release: diego
  lifecycle: errand
  instances: 1
  networks:
    - name: default
  resource_pool: small_errand

properties:
  diego:
    smoke_tests:
      api: (( meta.smoke_tests.api ))
      user: (( meta.smoke_tests.username ))
      password: (( meta.smoke_tests.password ))
      org: (( meta.smoke_tests.organization ))
      space: (( meta.smoke_tests.space ))

    ssl:
      skip_cert_verify: (( meta.smoke_tests.skip_ssl_validation ))
